name: panoptic_widgets
description: "A group of flutter widgets which are used in the Panoptic Family of Apps - created and maintained by Tonbridge School's Developers"
version: 2025.3.5
homepage: https://tonbridge-school.co.uk

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ai_barcode_scanner: ^6.0.1
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  csslib: ^1.0.2
  delightful_toast: ^1.1.0
  dio: ^5.8.0
  dotted_border: ^2.1.0
  easy_date_timeline: ^2.0.9
  excel: ^4.0.6
  file_picker: ^9.0.1
  flutter_colorpicker: ^1.1.0
  file_saver: ^0.2.14
  flutter_quill: ^11.0.0
  flutter_quill_delta_from_html: ^1.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_network: ^2.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  material_segmented_control: ^5.0.1
  measure_size_builder: ^1.0.3
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  syncfusion_flutter_core: ^28.2.7
  syncfusion_flutter_datagrid: ^28.2.7
  syncfusion_flutter_pdfviewer: ^28.2.7
  theme_provider: ^0.6.0
  toastification: ^3.0.1
  vsc_quill_delta_to_html: ^1.0.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  html: ^0.15.5
  logging: ^1.3.0
  flutter_xlider: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  test: 1.25.15
  integration_test:
    sdk: flutter
  build_runner: 2.4.15
  json_serializable: 6.9.4

dependency_overrides:
  collection: 1.19.1
  test_api: 0.7.4
  intl: ^0.20.2
  archive: ^4.0.0
#   #js: 0.7.1
#   intl: 0.19.0
#   http: 1.2.0
  
#   url_launcher_ios: 6.3.1
#   package_info_plus: 8.0.2
#   web: 1.0.0
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/icons_svg/
    - assets/animations/

  
